# Toy "metagenomics" data set to demo Altair library

In [1]:
import altair as alt
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

In [2]:
df = pd.read_csv('data/starwars_species_abundance.txt',sep='\t')
df

,site,reactor,run_id,sample_id,timestamp,rel_abund,organism,species_group
0,Takodana,R2D2,1,100,4-May-25,2,sarlacc,wiggly
1,Takodana,R2D2,1,100,4-May-25,18,mynok,flapper
2,Takodana,R2D2,1,100,4-May-25,40,aiwha,flapper
3,Takodana,R2D2,1,100,4-May-25,30,porg,flapper
4,Takodana,R2D2,1,100,4-May-25,10,ewok,pawsly
...,...,...,...,...,...,...,...,...
133,Takodana,R3D3,4,402,20-May-25,5,aiwha,flapper
134,Takodana,R3D3,4,402,20-May-25,49,porg,flapper
135,Takodana,R3D3,4,402,20-May-25,1,bantha,hoofed
136,Takodana,R3D3,4,402,20-May-25,30,fathier,hoofed
137,Takodana,R3D3,4,402,20-May-25,15,wompa,clawful

In [3]:
df[['organism','species_group']].value_counts()

organism  species_group
aiwha     flapper          22
porg      flapper          22
mynok     flapper          20
bantha    hoofed           17
tauntaun  clawful          17
fathier   hoofed           16
ewok      pawsly           12
sarlacc   wiggly            7
wompa     clawful           5
dtype: int64

In [4]:
df['species_group'].value_counts()

flapper    64
hoofed     33
clawful    22
pawsly     12
wiggly      7
Name: species_group, dtype: int64

In [5]:
# run 1
df1 = df[df['run_id'] == 1]
df1

,site,reactor,run_id,sample_id,timestamp,rel_abund,organism,species_group
0,Takodana,R2D2,1,100,4-May-25,2,sarlacc,wiggly
1,Takodana,R2D2,1,100,4-May-25,18,mynok,flapper
2,Takodana,R2D2,1,100,4-May-25,40,aiwha,flapper
3,Takodana,R2D2,1,100,4-May-25,30,porg,flapper
4,Takodana,R2D2,1,100,4-May-25,10,ewok,pawsly
5,Takodana,R2D2,1,101,5-May-25,5,sarlacc,wiggly
6,Takodana,R2D2,1,101,5-May-25,20,mynok,flapper
7,Takodana,R2D2,1,101,5-May-25,38,aiwha,flapper
8,Takodana,R2D2,1,101,5-May-25,32,porg,flapper
9,Takodana,R2D2,1,101,5-May-25,5,ewok,pawsly
10,Takodana,R2D2,1,102,6-May-25,25,mynok,flapper
11,Takodana,R2D2,1,102,6-May-25,32,aiwha,flapper
12,Takodana,R2D2,1,102,6-May-25,33,porg,flapper
13,Takodana,R2D2,1,102,6-May-25,3,ewok,pawsly
14,Takodana,R2D2,1,102,6-May-25,7,bantha,hoofed
15,Takodana,R2D2,1,103,7-May-25,21,mynok,flapper
16,Takodana,R2D2,1,103,7-May-25,25,aiwha,flapper
17,Takodana,R2D2,1,103,7-May-25,38,porg,flapper
18,Takodana,R2D2,1,103,7-May-25,2,ewok,pawsly
19,Takodana,R2D2,1,103,7-May-25,14,bantha,hoofed
20,Takodana,R2D2,1,104,8-May-25,14,mynok,flapper
21,Takodana,R2D2,1,104,8-May-25,22,aiwha,flapper
22,Takodana,R2D2,1,104,8-May-25,44,porg,flapper
23,Takodana,R2D2,1,104,8-May-25,4,ewok,pawsly
24,Takodana,R2D2,1,104,8-May-25,11,bantha,hoofed
25,Takodana,R2D2,1,104,8-May-25,5,tauntaun,clawful
26,Takodana,R2D2,1,105,9-May-25,14,mynok,flapper
27,Takodana,R2D2,1,105,9-May-25,21,aiwha,flapper
28,Takodana,R2D2,1,105,9-May-25,40,porg,flapper
29,Takodana,R2D2,1,105,9-May-25,2,ewok,pawsly
30,Takodana,R2D2,1,105,9-May-25,8,bantha,hoofed
31,Takodana,R2D2,1,105,9-May-25,15,tauntaun,clawful

## Stacked bar chart

In [6]:
alt.Chart(df1).mark_bar().encode(
    x = alt.X('timestamp:O'),
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
).interactive()

alt.Chart(...)

## Area chart

In [7]:
alt.Chart(df1).mark_area().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',aaa
    #detail='organism:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
).interactive()

alt.Chart(...)

## Line chart

In [8]:
alt.Chart(df1).mark_line().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',
    detail='organism:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N'],
    strokeDash='species_group:N'
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
).interactive()

alt.Chart(...)

## Scatterplot

In [9]:
alt.Chart(df1).mark_point().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    shape='species_group:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
).interactive()

alt.Chart(...)

## Points and Lines

In [10]:
points = alt.Chart(df1).mark_point().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    shape='species_group:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
)

lines = alt.Chart(df1).mark_line().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    detail='species_group:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).interactive()

points + lines

alt.LayerChart(...)

In [11]:
# use a base chart

base = alt.Chart(df1).encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'species_group:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N']
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
)

points = base.mark_point().encode(
    shape='species_group:N'
)

lines = base.mark_line().encode(
    #detail='organism:N'
)
points + lines

alt.LayerChart(...)

## Multiple runs

In [13]:
alt.Chart(df).mark_line().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',aaa
    #detail='run_id:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N'],
    column = 'reactor:N',
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 400,
    height = 400
).interactive()

alt.Chart(...)

## Legend select

In [14]:
selection = alt.selection_point(fields=['organism'], bind='legend')


base = alt.Chart(df).encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',aaa
    detail='run_id:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N'],
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 200
).interactive()

points = base.mark_point().encode(
    shape='species_group:N',
    size=alt.condition(selection, alt.value(100), alt.value(20))
).add_params(
    selection
)

lines = base.mark_line().encode(
    size=alt.condition(selection, alt.value(2), alt.value(0.5))
).add_params(
    selection
)

chart = points + lines
chart = chart.facet(
    row='reactor:N',
)
chart

alt.FacetChart(...)

## mouseover highlight

In [56]:
highlight = alt.selection_point(on='pointerover', fields=['organism'], nearest=True)

base = alt.Chart(df).encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',aaa
    detail='run_id:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N'],
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 200
).interactive()

points = base.mark_point().encode(
    shape='species_group:N',
    size=alt.condition(highlight, alt.value(100), alt.value(20))
).add_params(
    highlight
)

lines = base.mark_line().encode(
    size=alt.condition(highlight, alt.value(2), alt.value(0.5))
).add_params(
    highlight
)

chart = points + lines
chart = chart.facet(
    row='reactor:N',
)
chart

alt.FacetChart(...)

## Heatmap

In [ ]:
# average relative abundance of species by run_id and organism

alt.Chart(df).mark_rect().encode(
    x='run_id:O',
    y='species_group:N',
    color='average(rel_abund):Q',
    tooltip=['species_group:N', 'mean(rel_abund):Q','run_id:N','site:N',],
).properties(
    title='Species Abundance Heatmap',
    width=400,
    height=400
).interactive()

alt.Chart(...)

In [95]:
df[(df['species_group'] == 'hoofed') & (df['run_id'] == 1)]

,site,reactor,run_id,sample_id,timestamp,rel_abund,organism,species_group
14,Takodana,R2D2,1,102,6-May-25,7,bantha,hoofed
19,Takodana,R2D2,1,103,7-May-25,14,bantha,hoofed
24,Takodana,R2D2,1,104,8-May-25,11,bantha,hoofed
30,Takodana,R2D2,1,105,9-May-25,8,bantha,hoofed

## Texture Area chart

In [25]:
site = df1['site'].unique()[0]
run_id = df1['run_id'].unique()[0]

# Tableau 20 color palette for plotly
tableau_20 = [
    "#4E79A7", "#A0CBE8", "#F28E2B", "#FFBE7D","#59A14F", 
    "#8CD17D", "#B6992D", "#F1CE63", "#499894", "#86BCB6",
    "#E15759", "#FF9D9A", "#79706E", "#BAB0AC", "#D37295",
    "#FABFD2", "#B07AA1", "#D4A6C8", "#9D7660", "#D7B5A6",
]

# set column to be used as texture fill
df1['wings'] = df1['species_group'].apply(lambda x: 1 if x == 'flapper' else 0)
    

# plot the stacked area chart
fig = px.area(df1.sort_values('organism'), x="timestamp", y="rel_abund", 
            color="organism",
            color_discrete_sequence=tableau_20,
            hover_data=['organism','rel_abund','sample_id','species_group'],)

# change the y-axis label
fig.update_yaxes(title_text="Relative Abundance (%)")
    
#Loop through the traces and apply pattern fill based on the 'phage' column
for trace in fig.data:
    # Extract the name of the organism for the current trace
    organism_name = trace.name
    
    # Check if 'phage' is True for this organism
    if df1[df1['organism'] == organism_name]['wings'].iloc[0] == True:
        trace.update(fillpattern=dict(shape='x'))

# update the fillcolor of each trace to match the line color (not transparent)
fig.for_each_trace(lambda trace: trace.update(fillcolor = trace.line.color))

# remove background grid
fig.update_layout(
    plot_bgcolor='rgba(0,0,0,0)',
    title=f"{site} - {run_id}",
)

fig.show()

/var/folders/5x/schnys9534v9f2pxc13ffqlm0000gn/T/ipykernel_64625/1993815865.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# SCRATCH

In [18]:
alt.Chart(df).mark_area().encode(
    x = 'timestamp:T',
    y = 'rel_abund:Q',
    color = 'organism:N',
    #color = 'species_group:N',aaa
    #detail='organism:N',
    tooltip=['organism:N', 'species_group:N', 'rel_abund:Q', 'timestamp:O', 'run_id:N','site:N','sample_id:N'],
    row = 'reactor:N',
).properties(
    title = 'Run 1: Relative Abundance of Species Over Time',
    width = 800,
    height = 400
).interactive()

alt.Chart(...)